---
- name: Install MySQL packages
  sudo: yes
  yum: name={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-devel
    - MySQL-python

- name: Setup my.cnf
  sudo: yes
  template: src=my.cnf.tpl dest=/etc/my.cnf

- name: Start MySQL service
  sudo: yes
  service: name=mysqld state=started enabled=true

- name: Update root password for root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create database
  mysql_db: name={{ mysql.database }} state=present login_user=root login_password={{ mysql.root_password }}

- name: Create user
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} priv={{ mysql.database }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}